# Generated by Django 5.0.2 on 2024-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqolamodel',
            old_name='author',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='maqolamodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maqolamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqolamodel',
            name='tags',
            field=models.CharField(choices=[('Certificates', 'Certificates'), ('Projects', 'Projects'), ('Education', 'Education')], max_length=255),
        ),
    ]
