# Generated by Django 5.0.2 on 2024-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_author_maqolamodel_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqolamodel',
            name='link',
            field=models.CharField(default=-1, max_length=500),
            preserve_default=False,
        ),
    ]
