# Generated by Django 5.0.2 on 2024-06-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_maqolamodel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maqolamodel',
            name='link',
        ),
    ]
