# Generated by Django 5.0.2 on 2024-06-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_maqolamodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqolamodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
