# Generated by Django 5.0.2 on 2024-06-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_maqolamodel_description_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqolamodel',
            old_name='description',
            new_name='description_eng',
        ),
        migrations.RenameField(
            model_name='maqolamodel',
            old_name='description_uz',
            new_name='description_uzb',
        ),
    ]
