# Generated by Django 5.0.2 on 2024-06-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_description_maqolamodel_description_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolamodel',
            name='tags',
            field=models.CharField(blank=True, choices=[('Certificates', 'Certificates'), ('Projects', 'Projects'), ('Education', 'Education')], max_length=255, null=True),
        ),
    ]
