# Generated by Django 5.0.2 on 2024-06-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
