# Generated by Django 5.0.2 on 2024-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_maqola_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='tag',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('world', 'World'), ('sport', 'Sport')], max_length=15, null=True),
        ),
    ]
