# Generated by Django 5.0.4 on 2024-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='tag',
            field=models.CharField(choices=[('local', 'local'), ('word', 'world'), ('sport', 'sport')], default=-1, max_length=15),
            preserve_default=False,
        ),
    ]
