# Generated by Django 5.1.2 on 2024-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('finished', 'finished')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default=-1, max_length=120),
            preserve_default=False,
        ),
    ]
