# Generated by Django 5.0.2 on 2024-06-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forOrdering', '0008_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
