# Generated by Django 5.0.2 on 2024-05-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_maqola_image_alter_maqola_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='author',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='maqola',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='maqola',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maqola',
            name='description',
        ),
        migrations.AddField(
            model_name='maqola',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='rank',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maqola',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
