# Generated by Django 5.0.2 on 2024-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_author_maqola_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='tag',
            field=models.CharField(blank=True, choices=[('local', 'Staff'), ('world', 'Guest'), ('sport', 'Manager')], max_length=15, null=True),
        ),
    ]
