# Generated by Django 5.0.2 on 2024-06-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
