# Generated by Django 5.0.2 on 2024-06-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forProduct', '0007_remove_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
