# Generated by Django 5.0.2 on 2024-06-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forProduct', '0010_rename_nameofcategory_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
