# Generated by Django 5.0.2 on 2024-05-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeConf',
            new_name='CodeConfirmation',
        ),
    ]
