# Generated by Django 5.0.2 on 2024-06-03 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_codeconf_codeconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
