# Generated by Django 5.0.2 on 2024-06-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forProduct', '0003_category_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nameOfCategory',
        ),
    ]
