# Generated by Django 5.0.2 on 2024-06-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forProduct', '0008_alter_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nameOfCategory',
        ),
    ]
