# Generated by Django 5.0.2 on 2024-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forOrdering', '0009_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
